import type { UserRole } from "./user.types";

export interface BulkCreateUserInput {
  name: string;
  email: string;
  /** Optional — backend generates a strong random password if omitted. */
  password?: string;
  phone?: string;
  role: UserRole;
}

export interface BulkCreateUserResultOk {
  email: string;
  uid: string;
  /**
   * The password set on the new account — either echoed from input
   * or auto-generated. SAVE this from the response: the backend does
   * NOT persist it anywhere (only Firebase Auth's hashed copy remains).
   */
  password: string;
  /** True if the password was generated by the backend. */
  generated: boolean;
  status: "created";
}

export interface BulkCreateUserResultFail {
  email: string;
  status: "failed";
  error: string;
  code?: string;
}

export type BulkCreateUserResult = BulkCreateUserResultOk | BulkCreateUserResultFail;

export interface BulkCreateUsersResponse {
  total: number;
  created: number;
  failed: number;
  results: BulkCreateUserResult[];
}
